version: '3'               #このdocker-compose.ymlファイルの"書式"のバージョン
services:                  #サービスについて定義する。
  web:                   #nginxについて定義するという宣言。
    build: ./nginx         #Dockerfileのパス
    image: nginx:latest       #イメージ名を指定
    container_name: "chai"  #コンテナ名を指定
    ports:                 #ポート公開内容を指定する。
      - "8080:80"          #コンテナ側で80だとホスト側で8080となる。
    volumes:               #ホストのフォルダをコンテナに追加する。 ホスト側:コンテナ側
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf #コンフィグファイルをコピー
      - ./src:/var/www/html
      # - ./src:/usr/share/nginx/html         #ソースをコピー
    depends_on: 
      - "app"

  app:
    image: php:7.4-fpm
    volumes:
      # - ./nginx/html:/usr/share/nginx/html
      - ./src:/var/www/html
    depends_on: 
      - "db"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:  
      - "8888:80" 
    depends_on: 
      - "db"

  db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
