version: '3'             #フォーマットのバージョン。現在は3が最新。
services:                #アプリケーションを動かせるための記述
  web:                   #コンテナ名
    image: nginx:latest  #イメージ名
    ports:               #使用ポート
      - "8000:80"
    depends_on: #追記
      - app
    volumes: #以下を追記　[ホストのファイルパス]:[コンテナファイルパス]
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  app: #以下を追記
    image: php:7.2.15-fpm
    depends_on: #追記
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80